language: perl

branches:
    only:
    - master

perl:
    - "5.26"

install:
    - echo "" > /dev/null

script:
    - if find . -name '*.pl' -exec perl -c {} 2>&1 \; | grep "syntax error"; then exit 1; fi
